export enum ThemeOptionsEnum {
  CUSTOM = "Custom",
  DAWN = "Dawn",
  ELECTRIC = "Electric",
  FOREST = "Forest",
  SHADES_OF_GREY = "50 Shades of Grey",
  VIBRANT = "Vibrant",
  NEON = "Neon",
  VANILA = "Vanila",
  LOVE = "Love",
  EARTH = "Earth",
  VALENTINE = "Valentine",
  BUBBLE_GUM = "Bubble Gum",
  BLACK_AND_YELLOW = "Black and Yellow",
  SOPHISTICATED = "Sophisticated",
  FIRE = "Fire",
  FROST = "Frost",
  SUNNY_EVENING = "Sunny Evening",
  RED_MOON = "Red Moon",
  DARK_OCEAN = "Dark Ocean",
  MINIMAL = "Minimal",
  MINT = "Mint",
}

const announcementThemeOptions = [
  { label: "Custom", value: ThemeOptionsEnum.CUSTOM },
  { label: "Dawn", value: ThemeOptionsEnum.DAWN },
  { label: "Electric", value: ThemeOptionsEnum.ELECTRIC },
  { label: "Forest", value: ThemeOptionsEnum.FOREST },
  { label: "50 Shades of Grey", value: ThemeOptionsEnum.SHADES_OF_GREY },
  { label: "Vibrant", value: ThemeOptionsEnum.VIBRANT },
  { label: "Neon", value: ThemeOptionsEnum.NEON },
  { label: "Vanila", value: ThemeOptionsEnum.VANILA },
  { label: "Love", value: ThemeOptionsEnum.LOVE },
  { label: "Earth", value: ThemeOptionsEnum.EARTH },
  { label: "Valentine", value: ThemeOptionsEnum.VALENTINE },
  { label: "Bubble Gum", value: ThemeOptionsEnum.BUBBLE_GUM },
  { label: "Black and Yellow", value: ThemeOptionsEnum.BLACK_AND_YELLOW },
  { label: "Sophisticated", value: ThemeOptionsEnum.SOPHISTICATED },
  { label: "Fire", value: ThemeOptionsEnum.FIRE },
  { label: "Frost", value: ThemeOptionsEnum.FROST },
  { label: "Sunny Evening", value: ThemeOptionsEnum.SUNNY_EVENING },
  { label: "Red Moon", value: ThemeOptionsEnum.RED_MOON },
  { label: "Dark Ocean", value: ThemeOptionsEnum.DARK_OCEAN },
  { label: "Minimal", value: ThemeOptionsEnum.MINIMAL },
  { label: "Mint", value: ThemeOptionsEnum.MINT },
];

export default announcementThemeOptions;
